{
  "type": "record",
  "name": "Payment",
  "namespace": "com.bootcamp.payments",
  "fields": [
    {
      "name": "id",
      "type": "long"
    },
    {
      "name": "card_id",
      "type": "long",
      "confluent:tags": [
        "PCI"
      ]
    },
    {
      "name": "amount",
      "type": {
        "type": "bytes",
        "logicalType": "decimal",
        "precision": 15,
        "scale": 2
      }
    },
    {
      "name": "event_time",
      "type": {
        "type": "long",
        "logicalType": "timestamp-millis"
      }
    },
    {
      "name": "channel",
      "type": "string"
    }
  ]
}